"""empty message

Revision ID: 5f184db516ab
Revises: b1447e7bc524
Create Date: 2020-11-25 18:23:14.122245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f184db516ab'
down_revision = 'b1447e7bc524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('latitude', sa.Text(), nullable=True))
    op.add_column('photo', sa.Column('longitude', sa.Text(), nullable=True))
    op.drop_column('photo', 'coordinates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('coordinates', mysql.TEXT(), nullable=True))
    op.drop_column('photo', 'longitude')
    op.drop_column('photo', 'latitude')
    # ### end Alembic commands ###
