"""empty message

Revision ID: b1447e7bc524
Revises: 29e4fbaaa66e
Create Date: 2020-11-24 16:34:14.980935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1447e7bc524'
down_revision = '29e4fbaaa66e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('coordinates', sa.Text(), nullable=True))
    op.drop_column('photo', 'latitude')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('latitude', mysql.TEXT(), nullable=True))
    op.drop_column('photo', 'coordinates')
    # ### end Alembic commands ###
